_BASE_: "Base-CTW1500-Polygon.yaml"
MODEL:
  NUMBER_OF_CHANNEL: [192, 384, 768]
  #WEIGHTS: "output/TESTR/pretrain/TESTR_SWINT_Polygon/model_final.pth"
  WEIGHTS: "output/TESTR/under/TESTR_R_50_Polygon2/model_final.pth"
  #RESNETS:
  #  DEPTH: 50
  TRANSFORMER:
    NUM_FEATURE_LEVELS: 4
    ENC_LAYERS: 6
    DEC_LAYERS: 6
    DIM_FEEDFORWARD: 1024
    HIDDEN_DIM: 256
    DROPOUT: 0.1
    NHEADS: 8
    NUM_QUERIES: 100
    ENC_N_POINTS: 4
    DEC_N_POINTS: 4
SOLVER:
  STEPS: (1500000, 3500000)
  IMS_PER_BATCH: 1
  BASE_LR: 1e-5
  LR_BACKBONE: 1e-6
  WARMUP_ITERS: 0
  MAX_ITER: 4000000
  CHECKPOINT_PERIOD: 10000
TEST:
  EVAL_PERIOD: 10000
OUTPUT_DIR: "output/TESTR/ctw1500/TESTR_R_50_Polygon"
