_BASE_: "Base-TotalText-Polygon.yaml"
MODEL:
  NUMBER_OF_CHANNEL: [192, 384, 768]
  WEIGHTS: "output/TESTR/under/TESTR_R_50_Polygon3/model_0372999.pth"
  #WEIGHTS: "output/TESTR/pretrain/TESTR_SWINT_Polygon/model_final.pth"
  #RESNETS:
    #DEPTH: 50
  TRANSFORMER:
    NUM_FEATURE_LEVELS: 4
    ENC_LAYERS: 6
    DEC_LAYERS: 6
    DIM_FEEDFORWARD: 1024
    HIDDEN_DIM: 256
    DROPOUT: 0.1
    NHEADS: 8
    NUM_QUERIES: 100
    ENC_N_POINTS: 4
    DEC_N_POINTS: 4
SOLVER:
  IMS_PER_BATCH: 1
  BASE_LR: 2e-5
  LR_BACKBONE: 2e-6
  #LR_SCHEDULER_NAME: WarmupCosineLR
  #WARMUP_FACTOR: 0.00001
  WARMUP_ITERS: 0
  STEPS: (150000, 350000)
  MAX_ITER: 450000
  CHECKPOINT_PERIOD: 1000
TEST:
  EVAL_PERIOD: 1000
OUTPUT_DIR: "output/TESTR/totaltext/TESTR_SWINT_Polygon1155_domain"
