_BASE_: "../Base-TESTRswinv1.yaml"
DATASETS:
  #TRAIN: ("mltbezier_word_poly_train", "totaltext_poly_train", "syntext1_poly_train", "syntext2_poly_train", "icdar2015_train",) 
  TRAIN: ("rects_train", "rects_val", )
  
  TEST: ("rects_test",)
MODEL:
  TRANSFORMER:
    USE_POLYGON: True
    NUM_CTRL_POINTS: 16
    VOC_SIZE: 5463
    LOSS:
      POINT_TEXT_WEIGHT: 4.0
