_BASE_: "../Base-TESTRswinv1.yaml"
DATASETS:
  TRAIN: ("under_train","under_val",)
  TEST: ("under",)
MODEL:
  TRANSFORMER:
    USE_POLYGON: True
    NUM_CTRL_POINTS: 16
    LOSS:
      POINT_TEXT_WEIGHT: 4.0
TEST:
  USE_LEXICON: False
  LEXICON_TYPE: 3
  WEIGHTED_EDIT_DIST: False
INPUT:
  MIN_SIZE_TRAIN: (400, 800)
  MAX_SIZE_TRAIN: 1000
  MIN_SIZE_TEST: 400
  MAX_SIZE_TEST: 400
